### ISSUE TITLE
是否使用CPM预训练模型

### ISSUE THREAD

**Issue by bupticybee** [yangjianxin1/CPM#2]
清华CPM没有发布medium和small的pretrain weight，只发布了large和distill的权重，所以这个项目从头开始训练的么？

**Comment by yangjianxin1** [comment]
是的，这个项目是从头开始训练的

**Comment by bupticybee** [comment]
> 是的，这个项目是从头开始训练的

好的感谢

**Comment by KAndHisC** [comment]
distill也下不了了，大佬以前下过吗？可以分享一下吗？ @bupticybee
