### ISSUE TITLE
申请下载的只有large，你用的small在哪下载的

### ISSUE THREAD

**Issue by MaNing19243821415** [yangjianxin1/CPM#5]
请问一下那个CPM源码的CPM-small&CPM-medium两个模型的训练参数怎么找不到，申请下载的只有large，你用的small在哪下载的，

**Comment by KAndHisC** [comment]
> 请问一下那个CPM源码的CPM-small&CPM-medium两个模型的训练参数怎么找不到，申请下载的只有large，你用的small在哪下载的，
@MaNing1924382115  请问您找到了吗？
